### ISSUE TITLE
Main TODO

### ISSUE THREAD

**Issue by andreimarcu** [andreimarcu/linx-server#1]
__DEPRECATED__ (moved to separate issues)

In no particular order
- [ ] more tests
- [ ] /file/info
- [ ] display handlers
  - [x] random filetype
  - [x] images
  - [x] video
  - [ ] .story
  - [x] pastebin
  - [x] pdfs
  - [x] audio
  - [ ] .eml
  - [ ] markdown

- [ ] cleanup css
- [ ] twilio integration
- [ ] decide on error handling strategy
- [ ] decide what to be configurable (/"selif"/, etc), specify filenames, max filesize, 
  - [ ] https://github.com/walle/cfg
- [ ] decide to vendor dependencies
- [ ] albums / collections

Done:
- [x] API
- [x] switch to dropzone.js
- [x] cleanup js uploader file
- [x] torrent functionality
- [x] cache static files
- [x] add caching headers for static files
- [x] use go.rice to be able to ship a binary with embedded static assets for simple usage, but still be configurable with cli flags for advanced usage with nginx, etc https://gist.github.com/happierall/1048e57932adbfe2dcbe
- [x] respect randomized barename in request
- [x] delete files
- [x] 404 page
- [x] check if filename exists, increment it instead of replacing the file :laughing:
- [x] meta-data
  - [x] decide on best way, current linx way is filename_ file with expiry and delete key info
  - [x] file expiry (depends on a "serve file" method that would check the header file to see if needs to be deleted, etc)
  - [x] file delete keys
- [x] linx styling (including /static stuff) (minifying strategy?)
  - [x] add /static back
    - [x] have the app serve those assets, the user can always choose to override it by web server config
- [x] remote upload
- [x] show expiry on display
  - [x] use go-humanize
- [x] hotlink protection
- [x] json response on display urls
- [x] /paste/
- [x] add instructions on how to setup as reverse proxy with nginx
- [x] configurable flags for non-standalone usage (nginx serve static assets with x-accel-redirect), etc
  - [x] want people to be able to run the binary and have good defaults for the simplest use cases, then for any advanced usage change behavior through flags (default would be binding to 127.0.0.1:8080 versus a flag for fastcgi, etc)
